---
efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512MiB
userSwapChoices:
  - none
  - small
  - suspend
initialPartitioningChoice: erase
defaultFileSystemType: ext4
availableFileSystemTypes:
  - ext4
  - btrfs
  - xfs
