---
services:
  - name: sddm
    mandatory: false
  - name: NetworkManager
    mandatory: false
  - name: bluetooth
    mandatory: false
  - name: irqbalance
    mandatory: false
  - name: firewalld
    mandatory: false
timers: []
