---
defaultGroups:
  - wheel
autologinGroup: autologin
sudoersGroup: wheel
setRootPassword: true
doReusePassword: true
allowWeakPasswords: false
passwordRequirements:
  minLength: 6
  maxLength: -1
  libpwquality:
    - minlen=6
