# FRAMZ OS — настройки экрана входа.
# Если наша тема не понравится или что-то не так: замени Current=framz на Current=breeze
# и перезапусти службу: sudo systemctl restart sddm
[Theme]
Current=framz

[General]
Numlock=on
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Users]
MaximumUid=60000
MinimumUid=1000
