# FRAMZ OS — initramfs живого режима (флешка).
# Хуки archiso обязательны: именно они монтируют образ системы с флешки.
# plymouth — наш экран загрузки с самого начала.
HOOKS=(base udev plymouth modconf kms memdisk archiso archiso_loop_mnt archiso_pxe_common archiso_pxe_nbd archiso_pxe_http archiso_pxe_nfs block filesystems keyboard keymap consolefont)
COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-T0)
MODULES=()
BINARIES=()
FILES=()
